name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      id: prepare
      run: |
        DOCKER_IMAGE=${{ github.repository }}
        DOCKER_PLATFORMS=linux/amd64,linux/386,linux/ppc64le,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        VERSION=$(curl --silent "https://api.github.com/repos/slackhq/nebula/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
        TAGS="${DOCKER_IMAGE}:${VERSION}"
        TAGS="$TAGS,${DOCKER_IMAGE}:latest"
        echo ::set-output name=docker_username::${DOCKER_USERNAME}
        echo ::set-output name=docker_image::${DOCKER_IMAGE}
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=docker_platforms::${DOCKER_PLATFORMS}
        BUILDX_ARGS=$( \
          echo VERSION=${VERSION}; \
          echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ'); \
          echo VCS_REF=${GITHUB_SHA::8})
        BUILDX_ARGS="${BUILDX_ARGS//$'\n'/'%0A'}"
        echo ::set-output name=buildx_args::${BUILDX_ARGS}
        echo ::set-output name=tags::${TAGS}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
